force-app/main/default/objects/CountryDetail__c/CountryDetail__c.object-meta.xml
<CustomObject>
    <description>Object to hold country metadata from APIs such as Restcountries</description>
    <label>Country Detail</label>
    <nameField>
        <label>Country Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryDetail__c/fields/IsoCode3__c.field-meta.xml
<CustomField>
    <fullName>IsoCode3__c</fullName>
    <externalId>true</externalId>
    <label>Iso Code 3</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CountryDetailsSelector_Test.cls
@IsTest
private class CountryDetailsSelector_Test {
    @IsTest
    private static void getAllCountryDetails() {
        List<CountryDetail__c> countryDetailList = new List<CountryDetail__c>();

        for (Integer i = 0; i < 300; i++) {
            countryDetailList.add(
                new CountryDetail__c(
                    Name = String.valueOf(i),
                    IsoCode3__c = String.valueOf(i)
                )
            );
        }

        insert countryDetailList;

        ICountryDetailsSelector selector = CountryDetailsSelector.newInstance();
        List<CountryDetail__c> result = selector.getAllCountryDetails();
        System.assertEquals(300, result.size());
    }
}