force-app/main/default/objects/CountryDetail__c/CountryDetail__c.object-meta.xml
<CustomObject>
    <description>Object to hold country metadata from APIs such as Restcountries</description>
    <label>Country Detail</label>
    <nameField>
        <label>Country Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CountryDetail__c/fields/Capital__c.field-meta.xml
<CustomField>
    <fullName>Capital__c</fullName>
    <label>Capital</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountryDetail__c/fields/IsoCode2__c.field-meta.xml
<CustomField>
    <fullName>IsoCode2__c</fullName>
    <externalId>true</externalId>
    <label>Iso Code 2</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryDetail__c/fields/IsoCode3__c.field-meta.xml
<CustomField>
    <fullName>IsoCode3__c</fullName>
    <externalId>true</externalId>
    <label>Iso Code 3</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CountryDetail__c/fields/RegionalBlocs__c.field-meta.xml
<CustomField>
    <fullName>RegionalBlocs__c</fullName>
    <label>Regional Blocs</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CountryDetail__c/fields/Subregion__c.field-meta.xml
<CustomField>
    <fullName>Subregion__c</fullName>
    <label>Subregion</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CountryDetailsSelector.cls
public with sharing class CountryDetailsSelector extends fflib_SObjectSelector implements ICountryDetailsSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            CountryDetail__c.Id,
            CountryDetail__c.Name,
            CountryDetail__c.IsoCode2__c,
            CountryDetail__c.IsoCode3__c,
            CountryDetail__c.Capital__c,
            CountryDetail__c.Region__c,
            CountryDetail__c.Subregion__c,
            CountryDetail__c.RegionalBlocs__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return CountryDetail__c.sObjectType;
    }

    public static ICountryDetailsSelector newInstance() {
        return (ICountryDetailsSelector) Application.selector.newInstance(
            CountryDetail__c.sObjectType
        );
    }

    public List<CountryDetail__c> getAllCountryDetails() {
        return (List<CountryDetail__c>) Database.query(
            newQueryFactory().toSOQL()
        );
    }

    public Map<String, CountryDetail__c> getByCountryInLeads(
        Set<String> queriedValues
    ) {
        return null;
    }
}